name = "thryx-mcp-webhooks"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "API_KEYS"
id = "a3bcdca2d2154fdc804f279ca2a0eb7b"

[[kv_namespaces]]
binding = "CUSTOMERS"
id = "32e5871549054f3eb3ba2da05f8847fa"
